; Exercise 1.9: 
; Each of the following two procedures defines a method for adding two positive integers in terms of the procedures inc,
; which increments its argument by 1, and dec, which decrements its argument by 1.

#lang sicp

(define (processA a b)
  (if (= a 0) 
      b 
      (inc (processA (dec a) b))))

(processA 4 5)

(define (processB a b)
  (if (= a 0) 
      b 
      (processB (dec a) (inc b))))

(processB 4 5)

; Using the substitution model, illustrate the process generated by each procedure in evaluating (+ 4 5). 
; Are these processes iterative or recursive?

; Process A is recursive while Process B is iterative
;
; (processA 4 5)
; (inc ((processA 3 5))
; (inc (inc ((processA 2 5)))
; //////////
; (processB 4 5)
; (processB 3 6)
; (processB 2 7)
